---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by tangrenchu.
--- DateTime: 2023/2/12 00:43
---

setmetatable(_G, {
            __newindex = function (t, n, v)
               if string.sub(n,1,2) ~= 'f_' then
               	    error("Script attempted to create global variable '\"..tostring(n)..\"'", 2)
               else
                    rawset(t, n, v)
               end
            end,

            __index = function (t, n, v)
               if string.sub(n,1,2) ~= 'f_' then
                    error("attempt to read undeclared variable '"..tostring(n).."'", 2)
               end
            end,
        })